name: Setup PNPM
author: comma.ai
description: Setup PNPM for use in GitHub Actions

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4

    - uses: actions/setup-node@v4
      with:
        node-version-file: package.json
        cache: pnpm

    - shell: bash
      run: pnpm install --frozen-lockfile
