name: build

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - run: bun install --frozen-lockfile
      - run: bun pre-commit
      - run: bun run test
      - run: ./check-lines.sh

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - run: bun install --frozen-lockfile
      - run: bun run build

      - name: Upload built project
        uses: actions/upload-artifact@v4
        with:
          path: ./dist
          overwrite: true
          retention-days: 1
          name: build-artifacts-${{ github.run_id }}

  deploy:
    if: github.ref == 'refs/heads/master' && github.repository == 'commaai/new-connect'
    needs: [build, test]
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts-${{ github.run_id }}
          path: ./dist
          run-id: ${{ github.run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # deploy
      - name: Deploy to Cloudflare Pages
        id: cloudflare-publish
        uses: cloudflare/pages-action@v1.5.0
        with:
          directory: dist
          branch: new-connect
          projectName: connect
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_PAGES_TOKEN }}
          wranglerVersion: '3'
