name: PR Diff

on:
  pull_request_target:
    types: [assigned, opened, synchronize, reopened, edited]
    branches: [master]

concurrency:
  group: ${{ github.head_ref || github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  lines:
    name: Lint count diff
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout code from PR branch
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.sha }}
          path: pr
      - name: Checkout code from commaai master
        uses: actions/checkout@v4
        with:
          path: base
      - uses: oven-sh/setup-bun@v2
      - name: Create line count diff
        run: bun ./base/src/ci/check_lines.ts ./base/src ./pr/src > diff.txt
      - name: Comment diff
        uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b
        with:
          file-path: ./diff.txt
          comment-tag: diff
          github-token: ${{ secrets.GITHUB_TOKEN }}
